# -*- coding: utf-8 -*-
"""python B/solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wC5nAFNaGXNwKOjtb9FNoY6Liu6cAVp

# B. Cargo Craft Fleet

The total n must be made by: 4a + 6b = n

Because both 4 and 6 are even, if n is odd, it is impossible; also, the smallest possible total is 4, so if n < 4, impossible.

To get the minimum number of crafts, use as many 6s as possible; to get the maximum number of crafts, use as many 4s as possible.
"""

t = int(input())

for _ in range(t):
    n = int(input())
    if n < 4 or n % 2 == 1:
        print(-1)
    else:
        min_crafts = (n + 5) // 6 #equivalent to ceil(n/6)
        max_crafts = n // 4 #floor(n/4)
        print(min_crafts, max_crafts)